-- 20260309000000_add_america_europe_countries.sql
-- Add all countries from America and Europe

INSERT INTO countries (name, code) VALUES
-- America (North, Central, South, and Caribbean)
('Antigua y Barbuda', 'AG'),
('Bahamas', 'BS'),
('Barbados', 'BB'),
('Belice', 'BZ'),
('Bolivia', 'BO'),
('Brasil', 'BR'),
('Canadá', 'CA'),
('Chile', 'CL'),
('Costa Rica', 'CR'),
('Cuba', 'CU'),
('Dominica', 'DM'),
('Ecuador', 'EC'),
('El Salvador', 'SV'),
('Granada', 'GD'),
('Guatemala', 'GT'),
('Guyana', 'GY'),
('Haití', 'HT'),
('Honduras', 'HN'),
('Jamaica', 'JM'),
('Nicaragua', 'NI'),
('Panamá', 'PA'),
('Paraguay', 'PY'),
('Perú', 'PE'),
('República Dominicana', 'DO'),
('San Cristóbal y Nieves', 'KN'),
('San Vicente y las Granadinas', 'VC'),
('Santa Lucía', 'LC'),
('Surinam', 'SR'),
('Trinidad y Tobago', 'TT'),
('Uruguay', 'UY'),
('Venezuela', 'VE'),

-- Europe
('Albania', 'AL'),
('Alemania', 'DE'),
('Andorra', 'AD'),
('Armenia', 'AM'),
('Austria', 'AT'),
('Azerbaiyán', 'AZ'),
('Bélgica', 'BE'),
('Bielorrusia', 'BY'),
('Bosnia y Herzegovina', 'BA'),
('Bulgaria', 'BG'),
('Chipre', 'CY'),
('Ciudad del Vaticano', 'VA'),
('Croacia', 'HR'),
('Dinamarca', 'DK'),
('Eslovaquia', 'SK'),
('Eslovenia', 'SI'),
('Estonia', 'EE'),
('Finlandia', 'FI'),
('Francia', 'FR'),
('Georgia', 'GE'),
('Grecia', 'GR'),
('Hungría', 'HU'),
('Irlanda', 'IE'),
('Islandia', 'IS'),
('Italia', 'IT'),
('Kazajistán', 'KZ'),
('Letonia', 'LV'),
('Liechtenstein', 'LI'),
('Lituania', 'LT'),
('Luxemburgo', 'LU'),
('Macedonia del Norte', 'MK'),
('Malta', 'MT'),
('Moldavia', 'MD'),
('Mónaco', 'MC'),
('Montenegro', 'ME'),
('Noruega', 'NO'),
('Países Bajos', 'NL'),
('Polonia', 'PL'),
('Portugal', 'PT'),
('Reino Unido', 'GB'),
('República Checa', 'CZ'),
('Rumania', 'RO'),
('Rusia', 'RU'),
('San Marino', 'SM'),
('Serbia', 'RS'),
('Suecia', 'SE'),
('Suiza', 'CH'),
('Turquía', 'TR'),
('Ucrania', 'UA')
ON CONFLICT (name) DO NOTHING;
